/**
 * Unit tests for payuHash.ts.
 *
 * No test runner is wired on the backend in Sprint 1 — this file is written
 * as a plain module that `tsc --noEmit` type-checks, and can be executed
 * later under jest/vitest (or directly via ts-node) once a runner lands.
 *
 * The fixture vectors below were generated by running the PayU canonical
 * formulas against deterministic inputs with Node's built-in crypto. They
 * are self-consistent (they test that our implementation matches the spec
 * string shape) rather than mirrored from PayU's test-hash generator page,
 * because PayU does not publish a stable cross-merchant reference vector.
 * Sprint 2 PAY-010 should add one real sandbox round-trip test.
 */

import {
  buildPayuHashString,
  buildPayuResponseHashString,
  generatePayuHash,
  verifyPayuResponseHash,
} from '../payuHash'

type TestFn = () => void
const tests: Array<{ name: string; fn: TestFn }> = []
function test(name: string, fn: TestFn): void {
  tests.push({ name, fn })
}
function assertEq<T>(actual: T, expected: T, label: string): void {
  if (actual !== expected) {
    throw new Error(`${label}: expected ${String(expected)}, got ${String(actual)}`)
  }
}
function assertTrue(cond: boolean, label: string): void {
  if (!cond) throw new Error(`${label}: expected true`)
}

// --- Fixture ---------------------------------------------------------------

const FIXTURE = {
  key: 'JBZaLc',
  txnid: 'EB-TEST-123',
  amount: '1299.00',
  productinfo: 'Easebot Pro Monthly',
  firstname: 'Krish',
  email: 'test@example.com',
  udf1: 'uid_abc',
  udf2: 'pro',
  udf3: 'monthly',
  udf4: '',
  udf5: '',
  salt: 'eCwWELxi',
} as const

const EXPECTED_FORWARD_HASH =
  'cf166effa0ad4fc251f215641f85424c6a8c94507864326d7ec97c1093b1d836b2eae21119aee363282672523f562c791c9d6ac3eeb842925b0ac79967304cc2'

const EXPECTED_REVERSE_HASH =
  'd0898abf6aa6cb154541a13a8b7027b66b9b635413a36850b8c3c7acd7600631a0c2f5b096b56340d24fe75e4f664326dd30a2c6839634b9b976a8666c621f02'

// --- Tests -----------------------------------------------------------------

test('forward pre-hash string shape matches PayU §5 formula', () => {
  const s = buildPayuHashString(FIXTURE)
  // key|txnid|amount|productinfo|firstname|email|udf1|udf2|udf3|udf4|udf5||||||salt
  const expected =
    'JBZaLc|EB-TEST-123|1299.00|Easebot Pro Monthly|Krish|test@example.com|uid_abc|pro|monthly||||||||eCwWELxi'
  assertEq(s, expected, 'forward pre-hash')
})

test('generatePayuHash returns lowercase hex SHA-512 for fixture', () => {
  const h = generatePayuHash(FIXTURE)
  assertEq(h.length, 128, 'hash length (SHA-512 hex)')
  assertEq(h, h.toLowerCase(), 'lowercase')
  assertEq(h, EXPECTED_FORWARD_HASH, 'fixture hash')
})

test('missing UDFs default to empty string, not "undefined"', () => {
  const s = buildPayuHashString({
    key: FIXTURE.key,
    txnid: FIXTURE.txnid,
    amount: FIXTURE.amount,
    productinfo: FIXTURE.productinfo,
    firstname: FIXTURE.firstname,
    email: FIXTURE.email,
    salt: FIXTURE.salt,
    // udf1..udf5 intentionally omitted
  })
  assertTrue(!s.includes('undefined'), 'no "undefined" in pre-hash')
  assertTrue(s.endsWith('|eCwWELxi'), 'trailing salt preserved')
})

test('reverse pre-hash string shape matches PayU §5.1 formula', () => {
  const payload: Record<string, string> = {
    status: 'success',
    key: FIXTURE.key,
    txnid: FIXTURE.txnid,
    amount: FIXTURE.amount,
    productinfo: FIXTURE.productinfo,
    firstname: FIXTURE.firstname,
    email: FIXTURE.email,
    udf1: FIXTURE.udf1,
    udf2: FIXTURE.udf2,
    udf3: FIXTURE.udf3,
    udf4: FIXTURE.udf4,
    udf5: FIXTURE.udf5,
  }
  const s = buildPayuResponseHashString(payload, FIXTURE.salt)
  const expected =
    'eCwWELxi|success||||||||monthly|pro|uid_abc|test@example.com|Krish|Easebot Pro Monthly|1299.00|EB-TEST-123|JBZaLc'
  assertEq(s, expected, 'reverse pre-hash')
})

test('verifyPayuResponseHash accepts a correctly-signed payload', () => {
  const payload: Record<string, string> = {
    status: 'success',
    key: FIXTURE.key,
    txnid: FIXTURE.txnid,
    amount: FIXTURE.amount,
    productinfo: FIXTURE.productinfo,
    firstname: FIXTURE.firstname,
    email: FIXTURE.email,
    udf1: FIXTURE.udf1,
    udf2: FIXTURE.udf2,
    udf3: FIXTURE.udf3,
    udf4: FIXTURE.udf4,
    udf5: FIXTURE.udf5,
  }
  assertTrue(
    verifyPayuResponseHash(payload, EXPECTED_REVERSE_HASH, FIXTURE.salt),
    'valid signature',
  )
})

test('verifyPayuResponseHash rejects a tampered amount (LH-25/LH-29)', () => {
  const payload: Record<string, string> = {
    status: 'success',
    key: FIXTURE.key,
    txnid: FIXTURE.txnid,
    amount: '1.00', // tampered
    productinfo: FIXTURE.productinfo,
    firstname: FIXTURE.firstname,
    email: FIXTURE.email,
    udf1: FIXTURE.udf1,
    udf2: FIXTURE.udf2,
    udf3: FIXTURE.udf3,
    udf4: FIXTURE.udf4,
    udf5: FIXTURE.udf5,
  }
  assertTrue(
    !verifyPayuResponseHash(payload, EXPECTED_REVERSE_HASH, FIXTURE.salt),
    'tampered payload rejected',
  )
})

// --- Runner (invoked manually; no side effects on import) -----------------

export function runPayuHashTests(): { passed: number; failed: number } {
  let passed = 0
  let failed = 0
  for (const t of tests) {
    try {
      t.fn()
      passed++
    } catch (e) {
      failed++
      // eslint-disable-next-line no-console
      console.error(`FAIL ${t.name}:`, e)
    }
  }
  return { passed, failed }
}
