import type { NoteTemplate } from '@/types/notes'

export const NOTE_TEMPLATES: NoteTemplate[] = [
  {
    id: 'template-venue-comparison',
    title: 'Venue Comparison',
    description: 'Compare wedding venues side by side with ratings and notes.',
    icon: '\uD83C\uDFE9',
    category: 'venue',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Venue Comparison' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Use this template to compare potential wedding venues. Fill in each section for every venue you visit.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Venue 1' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Name: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Location: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Capacity: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Price: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Availability: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Pros: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Cons: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Rating (1-5): ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Venue 2' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Name: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Location: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Capacity: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Price: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Availability: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Pros: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Cons: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Rating (1-5): ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Final Decision' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Notes on final choice: ' }] },
      ],
    }),
  },
  {
    id: 'template-guest-list',
    title: 'Guest List',
    description: 'Track guests, RSVPs, dietary needs, and seating assignments.',
    icon: '\uD83D\uDC65',
    category: 'guest_list',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Guest List' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Track all your wedding guests, RSVPs, and seating arrangements.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Family - Side A' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name | RSVP: Pending | Dietary: None | Table: TBD' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Family - Side B' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name | RSVP: Pending | Dietary: None | Table: TBD' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Friends' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name | RSVP: Pending | Dietary: None | Table: TBD' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Summary' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total Invited: 0' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Confirmed: 0' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Declined: 0' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Pending: 0' }] }] },
        ] },
      ],
    }),
  },
  {
    id: 'template-wedding-day-timeline',
    title: 'Wedding Day Timeline',
    description: 'Hour-by-hour schedule for your wedding day.',
    icon: '\u23F0',
    category: 'ceremony',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Wedding Day Timeline' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Plan every moment of your big day from start to finish.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Morning Preparation' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '7:00 AM - Wake up, light breakfast' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '8:00 AM - Hair and makeup begins' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '10:00 AM - Get dressed' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '10:30 AM - First look / private moment' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '11:00 AM - Pre-ceremony photos' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Ceremony' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '1:00 PM - Guests arrive' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '1:30 PM - Ceremony begins' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '2:00 PM - Ceremony ends' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '2:15 PM - Family photos' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Reception' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '3:00 PM - Cocktail hour' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '4:00 PM - Grand entrance' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '4:30 PM - First dance' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '5:00 PM - Dinner served' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '6:00 PM - Toasts and speeches' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '7:00 PM - Cake cutting' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '7:30 PM - Open dancing' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '10:00 PM - Last dance and send-off' }] }] },
        ] },
      ],
    }),
  },
  {
    id: 'template-vendor-contacts',
    title: 'Vendor Contact Sheet',
    description: 'Keep all vendor contacts, contracts, and payment details organized.',
    icon: '\uD83D\uDCCB',
    category: 'vendor',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Vendor Contact Sheet' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Central hub for all vendor information, contracts, and payment schedules.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Photographer' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Name: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Phone: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Email: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Package: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total Cost: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Deposit Paid: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Balance Due: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Caterer' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Name: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Phone: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Email: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Menu: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total Cost: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Deposit Paid: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Balance Due: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Florist' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Name: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Phone: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Email: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Arrangements: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total Cost: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'DJ / Band' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Name: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Phone: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Email: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total Cost: ' }] }] },
        ] },
      ],
    }),
  },
  {
    id: 'template-budget-breakdown',
    title: 'Budget Breakdown',
    description: 'Track wedding expenses by category with estimated and actual costs.',
    icon: '\uD83D\uDCB0',
    category: 'budget',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Budget Breakdown' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Track your wedding budget with estimated and actual costs for each category.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Overall Budget' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total Budget: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total Spent: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Remaining: $' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Venue & Catering' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Venue Rental - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Catering - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Bar / Beverages - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Cake / Dessert - Estimated: $ | Actual: $' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Attire & Beauty' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Wedding Dress / Suit - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Alterations - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Hair & Makeup - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Accessories - Estimated: $ | Actual: $' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Decor & Flowers' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Flowers - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Decorations - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Lighting - Estimated: $ | Actual: $' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Entertainment & Media' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Photography - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Videography - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'DJ / Band - Estimated: $ | Actual: $' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Miscellaneous' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Invitations - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Favors - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Transportation - Estimated: $ | Actual: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Tips & Gratuities - Estimated: $ | Actual: $' }] }] },
        ] },
      ],
    }),
  },
  {
    id: 'template-ceremony-script',
    title: 'Ceremony Script',
    description: 'Draft your ceremony with vows, readings, and order of events.',
    icon: '\uD83D\uDC8D',
    category: 'ceremony',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Ceremony Script' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Draft and refine your wedding ceremony from processional to recessional.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Processional' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Music selection: ' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Order of entrance: ' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Welcome & Opening' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Officiant welcome remarks go here. Introduce the couple and set the tone for the ceremony.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Readings' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Reading 1 - Reader: ' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Text: ' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Reading 2 - Reader: ' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Text: ' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Vows' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Partner A vows: ' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Partner B vows: ' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Ring Exchange' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Ring bearer: ' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Ring exchange words: ' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Declaration & Kiss' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Officiant declaration: ' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Recessional' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Music selection: ' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Order of exit: ' }] },
      ],
    }),
  },
  {
    id: 'template-seating-chart',
    title: 'Seating Chart',
    description: 'Table-based seating arrangement for your reception.',
    icon: '\uD83D\uDCBA',
    category: 'reception',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Seating Chart' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Organize your reception seating. List guests under each table and note any special requirements.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Head Table' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Seat 1: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Seat 2: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Seat 3: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Seat 4: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Seat 5: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Seat 6: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Table 1' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Table 2' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Table 3' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest | Dietary: None' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Special Notes' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Wheelchair access needed: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'High chair needed: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Keep apart: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Keep together: ' }] }] },
        ] },
      ],
    }),
  },
  {
    id: 'template-thank-you-tracker',
    title: 'Thank You Note Tracker',
    description: 'Checklist to track thank you notes sent to each guest.',
    icon: '\u2709\uFE0F',
    category: 'guest_list',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Thank You Note Tracker' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Keep track of which guests have received thank you notes. Check off each one as you send it.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Family' }] },
        { type: 'taskList', content: [
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name - Gift: ___ | Note Sent: No' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name - Gift: ___ | Note Sent: No' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name - Gift: ___ | Note Sent: No' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Friends' }] },
        { type: 'taskList', content: [
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name - Gift: ___ | Note Sent: No' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name - Gift: ___ | Note Sent: No' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name - Gift: ___ | Note Sent: No' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Coworkers & Others' }] },
        { type: 'taskList', content: [
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name - Gift: ___ | Note Sent: No' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Guest Name - Gift: ___ | Note Sent: No' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Summary' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total Thank Yous Needed: 0' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Sent: 0' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Remaining: 0' }] }] },
        ] },
      ],
    }),
  },
  {
    id: 'template-honeymoon-itinerary',
    title: 'Honeymoon Itinerary',
    description: 'Day-by-day travel plan for your honeymoon trip.',
    icon: '\u2708\uFE0F',
    category: 'honeymoon',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Honeymoon Itinerary' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Plan your honeymoon day by day. Include flights, hotels, activities, and reservations.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Trip Details' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Destination: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Dates: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Budget: $' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Passport / Visa Status: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Travel Insurance: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Day 1 - Arrival' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Flight: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Hotel Check-in: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Dinner Reservation: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Day 2' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Morning: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Afternoon: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Evening: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Day 3' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Morning: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Afternoon: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Evening: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Day 4 - Departure' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Hotel Check-out: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Return Flight: ' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Packing List' }] },
        { type: 'taskList', content: [
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Passports & travel documents' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Sunscreen & toiletries' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Camera / chargers' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Swimwear' }] }] },
          { type: 'taskItem', attrs: { checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Evening outfits' }] }] },
        ] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Booking Confirmations' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Flight Confirmation #: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Hotel Confirmation #: ' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Car Rental Confirmation #: ' }] }] },
        ] },
      ],
    }),
  },
]
